name: CI

on:
  push:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          include-prerelease: true

      - name: Restore
        run: dotnet restore

      - name: Run dotnet format
        run: dotnet format VirusSimulation.csproj --verify-no-changes --no-restore

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          include-prerelease: true

      - name: Restore
        run: dotnet restore && dotnet restore tests/VirusSimulation.Tests

      - name: Build tests
        run: dotnet build tests/VirusSimulation.Tests --no-restore

      - name: Run tests
        run: dotnet test tests/VirusSimulation.Tests --no-build --verbosity normal
